apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo-container
        image: muskan1321/react-app
        ports:
        - containerPort: 3000
